name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v5

      - name: ğŸ“¦ Install Node dependencies
        run: npm install

      - name: ğŸ—ï¸ Build Frontend
        run: npm run build

      - name: ğŸ“‚Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ vars.FTP_SERVER_DIR }}
          protocol: ${{ vars.PROTOCOL }}
          port: ${{ vars.FTP_PORT }}

      - name: ğŸ“‚ Sync Public
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: ${{ vars.FTP_SERVER_PUBLIC_DIR }}
          protocol: ${{ vars.PROTOCOL }}
          port: ${{ vars.FTP_PORT }}
